### ISSUE TITLE
`rmt -r` does not work in versions prior to Redis 3.0

### ISSUE THREAD

**Issue by tao12345666333** [leonchen83/redis-rdb-cli#6]
The `RESTORE` command add in Redis 2.6,  `REPLACE` option add in Redis 3.0.

If we use `rmt -r` in versions prior to Redis 3.0, it doesn't work fine.

https://github.com/leonchen83/redis-rdb-cli/blob/master/src/main/java/com/moilioncircle/redis/rdb/cli/ext/rmt/SingleRdbVisitor.java#L95-L99

```java
if (!replace) {  
    endpoint.get().batch(flush, RESTORE, dkv.getKey(), expire, dkv.getValue());  
} else {  
    endpoint.get().batch(flush, RESTORE, dkv.getKey(), expire, dkv.getValue(), REPLACE);  
}  
```

Should we replace the implementation of Replace with Lua?

**Comment by leonchen83** [comment]
LGTM
I will fix this issue this weekend. Thx to report

**Comment by leonchen83** [comment]
Hi @tao12345666333 
```java  
# Redis-5.x : `dump_rdb_version=9`
# Redis-4.x : `dump_rdb_version=8`
# Redis-3.2 : `dump_rdb_version=7`
# Redis-3.0 : `dump_rdb_version=6`
# Redis-2.8 : `dump_rdb_version=6`
# Redis-2.6 : `dump_rdb_version=6`
```
redis 2.6 - 3.0 use the same rdb version 6 in dump file . so we can 't recognize the concrete redis version via rdb version. 

The work around about this issue is add  additional parameter in `rmt` command to show us the version like following

`rmt -s redis://120.0.0.1:6379 -m redis://127.0.0.1:6380 -r --legacy` means using lua script to migrate data in redis 2.6

**Comment by tao12345666333** [comment]
Thanks, I will test next week. :+1:

**Comment by leonchen83** [comment]
Fixed
